#!/bin/bash

filas=$1
columnas=$2

if [ -z "$filas" ]; then
    exit 1
fi

if [ -z "$columnas" ]; then
    exit 1
fi

for fila in $(seq 1 $filas ); do
    echo "<tr>"
    for columna in $(seq 1 $columnas ); do
        echo -e "\t<td>"$(echo $fila \* $columna | bc)"</td>"
    done
    echo "</tr>"
done
